###############################################################################
# FOR PIGEONPOSSE USAGE
###############################################################################

web:
  pigeonSH:
    name: "Pigeon SH"
    type:
      - cli
      - bin
      - library
    status: "active"
    version: "0.9.1"
    homepage: https://www.npmjs.com/package/@pigeon-posse/pigeonsh
    desc: "Centralize your server scripts in a single folder and run them using a command"
    logo: "https://raw.githubusercontent.com/pigeonposse/pigeonsh/main/docs/logo.png"
    banner: "https://raw.githubusercontent.com/pigeonposse/pigeonsh/main/docs/header.png"
###############################################################################
